name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      # Definir permissões de execução para o script
      - name: Set execute permission for the script
        run: chmod +x increment_version.sh

      # Executar o script para incrementar a versão
      - name: Run increment_version.sh
        id: version
        run: |
          ./increment_version.sh
          echo "::set-output name=version::$new_version"
        shell: /usr/bin/bash -e {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Etapa para criar e empurrar a tag
      - name: Create tag
        if: steps.version.outputs.version != '1.0.0'
        run: git tag v${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push tag
        if: steps.version.outputs.version != '1.0.0'
        run: git push origin v${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
