name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      # Fetch all tags
      - name: Fetch all tags
        run: git fetch --tags

      # Create version.txt if it doesn't exist
      - name: Create version.txt
        run: touch version.txt

      # Set execute permission for the script
      - name: Set execute permission for the script
        run: chmod +x increment_version.sh

      # Run the script to increment the version
      - name: Run increment_version.sh
        id: increment_version
        run: |
          ./increment_version.sh
          echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      # Create and push tag
      - name: Create and push tag
        run: |
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
