
name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      # Etapa para determinar a próxima versão
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install jq
        run: sudo apt-get install jq

      - name: Determine next version
        id: version
        run: |
          bash ./increment_version.sh
          echo "::set-output name=version::$new_version"

      # Etapa para criar e empurrar a tag, se necessário
      - name: Create and push tag
        if: steps.version.outputs.version != '1.0.0' # Skip if initial version
        run: |
          git tag v${{ steps.version.outputs.version }}
          git push origin v${{ steps.version.outputs.version }}

      # Etapa para construir e empurrar a imagem Docker
      - name: Build and push Docker image
        if: steps.version.outputs.version != '1.0.0' # Skip if initial version
        run: |
          docker build -t my-docker-repo/my-app:${{ steps.version.outputs.version }} .
          docker push my-docker-repo/my-app:${{ steps.version.outputs.version }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
