name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Determine new version
        id: determine_version
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null)

          if [ -z "$latest_tag" ]; then
            new_version="1.0.0"
          else
            major=$(echo "$latest_tag" | cut -d. -f1)
            minor=$(echo "$latest_tag" | cut -d. -f2)
            patch=$(echo "$latest_tag" | cut -d. -f3)
            
            if [ "$major" -eq "0" ]; then
              minor=$((minor + 1))
            else
              major=$((major + 1))
            fi
            
            new_version="$major.$minor.$patch"
          fi

          echo "::set-output name=version::$new_version"

      - name: Run tests
        run: npm test

      - name: Build and publish
        run: |
          # Use the determined version
          echo "New version: ${{ steps.determine_version.outputs.version }}"
          # Add your build and publish commands here using the determined version
