name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      # Set execute permission for the script
      - name: Set execute permission for the script
        run: chmod +x increment_version.sh

      # Run the script to increment the version
      - name: Run increment_version.sh
        id: version
        run: |
          ./increment_version.sh
          echo "New version: ${{ env.VERSION }}"

      # Create and push the tag
      - name: Create and push tag
        if: steps.version.outputs.version != '1.0.0'
        run: |
          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }}
