name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      # Create version.txt if it doesn't exist
      - name: Create version.txt
        run: touch version.txt

      # Set execute permission for the script
      - name: Set execute permission for the script
        run: chmod +x increment_version.sh

      # Run the script to increment the version
      - name: Run increment_version.sh
        id: version
        run: |
          ./increment_version.sh
          echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      # Check if the new version tag already exists
      - name: Check if tag already exists
        run: |
          if git rev-parse "v${{ steps.version.outputs.version }}" >/dev/null 2>&1; then
            echo "::error::Tag v${{ steps.version.outputs.version }} already exists. Skipping tag creation."
            exit 1
          fi

      # Create and push tag
      - name: Create and push tag
        run: |
          git tag v${{ steps.version.outputs.version }}
          git push origin --tags
