name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      # Etapa para determinar a nova versão
      - name: Determine new version
        id: version
        run: |
          if [[ -z $(git tag -l) ]]; then
            new_version="1.0.0"
          else
            latest_version=$(git describe --abbrev=0 --tags)
            major=$(echo $latest_version | cut -d. -f1)
            minor=$(echo $latest_version | cut -d. -f2)
            patch=$(echo $latest_version | cut -d. -f3)
            if [[ $patch == "0" ]]; then
              new_version="$major.$minor.1"
            else
              new_version="$major.$minor.$((patch+1))"
            fi
          fi
          echo "::set-output name=version::$new_version"
        shell: /usr/bin/bash -e {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     # Etapa para criar e empurrar a tag
      - name: Create tag
        if: steps.version.outputs.version != '1.0.0'
        run: git tag v${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push tag
        if: steps.version.outputs.version != '1.0.0'
        run: git push origin v${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    