name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      # Create version.txt if it doesn't exist
      - name: Create version.txt
        run: touch version.txt

      # Set execute permission for the script
      - name: Set execute permission for the script
        run: chmod +x increment_version.sh

      # Run the script to increment the version
      - name: Run increment_version.sh
        id: version
        run: ./increment_version.sh

      # Read the version from the file
      - name: Read version from file
        id: read_version
        run: echo "::set-output name=version::$(cat version.txt)"

      # Create and push tag
      - name: Create and push tag
        if: steps.read_version.outputs.version != '1.0.0'
        run: |
          git tag v${{ steps.read_version.outputs.version }}
          git push origin --tags
