name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      # Set execute permission for the script
      - name: Set execute permission for the script
        run: chmod +x increment_version.sh

      # Get the latest tag version
      - name: Get latest tag version
        id: latest_tag
        run: echo "latest_tag=$(git describe --tags --abbrev=0)" >> $GITHUB_STATE

      # Run the script to increment the version
      - name: Run increment_version.sh
        id: version
        run: |
          ./increment_version.sh
          echo "VERSION=$(cat $GITHUB_OUTPUT)" >> $GITHUB_STATE

      # Create and push tag
      - name: Create and push tag
        if: steps.version.outputs.version != '1.0.0'
        run: |
          git tag v${{ env.VERSION }}
          git push origin --tags
